### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by harishankarv** [mars-research/DRAMHiT#5]
- [ ] Tests with different prefetch window sizes
- [ ] Investigate why 120 cycles if (should not be 120 cycles if hash (25) + memcpy + memcmp (65) = 90 cycles. 
- [ ] Test with producer-consumer based prefetch queue : make insertion queue pipelined. (nice to have) 
- [x] Check 4096 logic: what if we do a naiive split and don't account for 4096 while splitting?
- [ ] depending on the above, add spill logic (last thread needn't be spawned maybe)
